//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmadSanitary {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class DateSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DateSettings defaultInstance = ((DateSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DateSettings())));
        
        public static DateSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2018-03-02")]
        public global::System.DateTime daily_date {
            get {
                return ((global::System.DateTime)(this["daily_date"]));
            }
            set {
                this["daily_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2028-01-01")]
        public global::System.DateTime exp_date {
            get {
                return ((global::System.DateTime)(this["exp_date"]));
            }
            set {
                this["exp_date"] = value;
            }
        }
    }
}
